FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.22 AS builder
WORKDIR /go/src/github.com/openshift/jetstack-cert-manager
COPY . .

ENV GO_BUILD_TAGS "strictfipsruntime,openssl"
ENV GOEXPERIMENT strictfipsruntime 
ENV CGO_ENABLED 1
ENV GOFLAGS ""

RUN go env
RUN cd cmd/acmesolver && go build -o _output/acmesolver -trimpath -ldflags '-w -s -X github.com/cert-manager/cert-manager/pkg/util.AppVersion=v1.15.0 -X github.com/cert-manager/cert-manager/pkg/util.AppGitCommit=7253cbd48b8905f06528f3d25e4d7dc4b975c9e2' -tags $GO_BUILD_TAGS main.go
RUN cd cmd/cainjector && go build -o _output/cainjector -trimpath -ldflags '-w -s -X github.com/cert-manager/cert-manager/pkg/util.AppVersion=v1.15.0 -X github.com/cert-manager/cert-manager/pkg/util.AppGitCommit=7253cbd48b8905f06528f3d25e4d7dc4b975c9e2' -tags $GO_BUILD_TAGS main.go
RUN cd cmd/controller && go build -o _output/controller -trimpath -ldflags '-w -s -X github.com/cert-manager/cert-manager/pkg/util.AppVersion=v1.15.0 -X github.com/cert-manager/cert-manager/pkg/util.AppGitCommit=7253cbd48b8905f06528f3d25e4d7dc4b975c9e2' -tags $GO_BUILD_TAGS main.go
RUN cd cmd/webhook && go build -o _output/webhook -trimpath -ldflags '-w -s -X github.com/cert-manager/cert-manager/pkg/util.AppVersion=v1.15.0 -X github.com/cert-manager/cert-manager/pkg/util.AppGitCommit=7253cbd48b8905f06528f3d25e4d7dc4b975c9e2' -tags $GO_BUILD_TAGS main.go

FROM registry.redhat.io/rhel9-2-els/rhel:9.2-1327.1725390050
WORKDIR /go/src/github.com/openshift/jetstack-cert-manager
COPY --from=builder _output/acmesolver /app/cmd/acmesolver/acmesolver
COPY --from=builder _output/cainjector /app/cmd/cainjector/cainjector
COPY --from=builder _output/controller /app/cmd/controller/controller
COPY --from=builder _output/webhook /app/cmd/webhook/webhook

USER 65534:65534

LABEL com.redhat.component="jetstack-cert-manager-acmesolver-container" \
      name="cert-manager/jetstack-cert-manager-acmesolver-rhel9" \
      version="v${CI_JETSTACK_CERT_MANAGER_UPSTREAM_VERSION_SANITIZED}" \
      summary="cert-manager-acmesolver" \
      maintainer="Red Hat, Inc." \
      description="jetstack-cert-manager-acmesolver-container" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images,cert-manager-acmesolver" \
      io.openshift.build.commit.id="${CI_JETSTACK_CERT_MANAGER_UPSTREAM_COMMIT}" \
      io.openshift.build.source-location="${CI_JETSTACK_CERT_MANAGER_UPSTREAM_URL}" \
      io.openshift.build.commit.url="${CI_JETSTACK_CERT_MANAGER_UPSTREAM_URL}/commit/${CI_JETSTACK_CERT_MANAGER_UPSTREAM_COMMIT}" \
      io.k8s.display-name="cert-manager-acmesolver" \
      io.k8s.description="jetstack-cert-manager-acmesolver-container"

ENTRYPOINT ["/app/cmd/acmesolver/acmesolver"]
